version: '2'
services:
  shogun-postgis:
    image: postgis/postgis:13-3.1-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: shogun
      POSTGRES_PASSWORD: shogun
    volumes:
      - ./shogun-postgis/postgresql_data:/var/lib/postgresql/data:Z
      - ./shogun-postgis/init_data/01_init_keycloak.sql:/docker-entrypoint-initdb.d/01_init_keycloak.sql
  shogun-redis:
    image: redis:6.2.1-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_PASS_FILE=/config/.redis
    command: [
        "sh",
        "-c",
        '
        docker-entrypoint.sh
        "/config/redis.conf"
        --requirepass "$$(cat $$REDIS_PASS_FILE)"
        ',
      ]
    volumes:
      - ./shogun-redis/redis_data:/data
      - ./shogun-redis/redis_config:/config
  shogun-keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - 8000:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: shogun
      DB_VENDOR: postgres
      DB_ADDR: shogun-postgis
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: shogun
      DB_PASSWORD: shogun
    depends_on:
      - shogun-postgis
