version: '2'
services:
  shogun-nginx:
    image: nginx:1.21.1
    volumes:
      - ./shogun-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./shogun-nginx/ssl/private/localhost.crt:/etc/nginx/ssl/private/localhost.crt
      - ./shogun-nginx/ssl/private/localhost.key:/etc/nginx/ssl/private/localhost.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - shogun-keycloak
      - shogun-boot
  shogun-geoserver:
    build:
      context: ./shogun-geoserver
      args:
        USER_UID: ${UID}
        USER_GID: ${GID}
        USER_NAME: ${UNAME}
    ports:
      - "8001:8080"
    environment:
      EXTRA_JAVA_OPTS: "-Xms1g -Xmx2g -DGEOSERVER_CSRF_WHITELIST=localhost"
    volumes:
      - ./shogun-geoserver/geoserver_data:/opt/geoserver_data/:Z
      - ./shogun-geoserver/additional_libs:/opt/additional_libs/:Z
  shogun-postgis:
    image: postgis/postgis:13-3.1-alpine
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./shogun-postgis/postgresql_data:/var/lib/postgresql/data:Z
      - ./shogun-postgis/init_data/01_init_keycloak.sql:/docker-entrypoint-initdb.d/01_init_keycloak.sql
  shogun-redis:
    image: redis:6.2.1-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASS_FILE=/config/.redis
    command: [
      "sh",
      "-c",
      '
      docker-entrypoint.sh
      "/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      ',
    ]
    volumes:
      - ./shogun-redis/redis_data:/data
      - ./shogun-redis/redis_config:/config
  shogun-keycloak:
    image: jboss/keycloak:14.0.0
    ports:
      - "8000:8080"
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: shogun-postgis
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - shogun-postgis
