version: '3.7'
services:
  shogun-geoserver:
    extends:
      file: ./common-services.yml
      service: shogun-geoserver
    build:
      context: ./shogun-geoserver
      args:
        USER_UID: ${UID}
        USER_GID: ${GID}
        USER_NAME: ${UNAME}
    ports:
      - "8001:8080"
  shogun-postgis:
    extends:
      file: ./common-services.yml
      service: shogun-postgis
    ports:
      - "5555:5432"
  shogun-redis:
    extends:
      file: ./common-services.yml
      service: shogun-redis
    ports:
      - "6379:6379"
  shogun-keycloak:
    extends:
      file: ./common-services.yml
      service: shogun-keycloak
    ports:
      - "8000:8080"
  shogun-nginx:
    extends:
      file: ./common-services.yml
      service: shogun-nginx
  shogun-client:
    extends:
      file: ./common-services.yml
      service: shogun-client
    build:
      context: ${SHOGUN_CLIENT_DIR}
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ${SHOGUN_CLIENT_DIR}:/app
  shogun-admin:
    extends:
      file: ./common-services.yml
      service: shogun-admin
    build:
      context: ${SHOGUN_ADMIN_DIR}
      dockerfile: Dockerfile.dev
    ports:
      - 9090:9090
    volumes:
      - ${SHOGUN_ADMIN_DIR}:/app
  shogun-boot:
    container_name: ${CONTAINER_NAME_PREFIX}-boot
    extends:
      file: ./common-services.yml
      service: shogun-boot
    build:
      context: ${SHOGUN_DIR}/shogun-boot/
    ports:
      - "8080:8080"
      - "4711:4711"
      - "9010:9010"
    volumes:
      - ${SHOGUN_DIR}/:/shogun/
      - ~/.m2:/root/.m2
  shogun-gs-interceptor:
    extends:
      file: ./common-services.yml
      service: shogun-gs-interceptor
