version: '2'
services:
  postgis:
    image: postgis/postgis:13-master
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: shogun
      POSTGRES_PASSWORD: shogun
    volumes:
      - ./postgis/postgresql_data:/var/lib/postgresql/data:Z
      - ./postgis/init_data/01_init_keycloak.sql:/docker-entrypoint-initdb.d/01_init_keycloak.sql
      - ./postgis/init_data/02_add_keycloak_data.sh:/docker-entrypoint-initdb.d/02_add_keycloak_data.sh
      - ./postgis/init_data/keycloak_data:/docker-entrypoint-initdb.d/keycloak_data:Z
  redis:
    image: library/redis:6-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_PASS_FILE=/config/.redis
    command: [
        "sh",
        "-c",
        '
        docker-entrypoint.sh
        "/config/redis.conf"
        --requirepass "$$(cat $$REDIS_PASS_FILE)"
        ',
      ]
    volumes:
      - ./redis/redis_data:/data
      - ./redis/redis_config:/config
  keycloak:
    image: jboss/keycloak:11.0.2
    ports:
      - 8000:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: shogun
      DB_VENDOR: postgres
      DB_ADDR: postgis
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: shogun
      DB_PASSWORD: shogun
