version: '3.7'
services:
  shogun-print:
    extends:
      file: ./common-services.yml
      service: shogun-print
    restart: unless-stopped
  shogun-geoserver:
    extends:
      file: ./common-services.yml
      service: shogun-geoserver
    image: terrestris/geoserver:2.22.2
    restart: unless-stopped
  shogun-postgis:
    extends:
      file: ./common-services.yml
      service: shogun-postgis
    restart: unless-stopped
  shogun-keycloak:
    extends:
      file: ./common-services.yml
      service: shogun-keycloak
    restart: unless-stopped
  shogun-nginx:
    extends:
      file: ./common-services.yml
      service: shogun-nginx
    volumes:
      - ./shogun-nginx/prod/default.conf:/etc/nginx/templates/default.conf.template
    restart: unless-stopped
  shogun-admin:
    extends:
      file: ./common-services.yml
      service: shogun-admin
    image: docker-public.terrestris.de/terrestris/shogun-admin:11.3.0
    restart: unless-stopped
  shogun-client:
    extends:
      file: ./common-services.yml
      service: shogun-client
    image: docker-public.terrestris.de/terrestris/shogun-gis-client:5.1.3
    restart: unless-stopped
  shogun-boot:
    extends:
      file: ./common-services.yml
      service: shogun-boot
    image: docker-public.terrestris.de/shogun/shogun-boot:16.2.0
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx512m -Djdk.serialSetFilterAfterRead=true -Dspring.config.location=/config/application.yml"
    restart: unless-stopped
  shogun-gs-interceptor:
    extends:
      file: ./common-services.yml
      service: shogun-gs-interceptor
    image: docker-public.terrestris.de/shogun/shogun-gs-interceptor:16.2.0
    restart: unless-stopped
  shogun-solr:
    extends:
      file: ./common-services.yml
      service: shogun-solr
    restart: unless-stopped
