version: '2'
services:
  postgis:
    image: mdillon/postgis:11-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: shogun
      POSTGRES_PASSWORD: shogun
    volumes:
      - ./postgis/postgresql_data:/var/lib/postgresql/data:Z
  redis:
    image: library/redis:5.0.7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis_data:/data

