version: '2'
services:
  shogun-nginx:
    image: nginx:1.21.1
    volumes:
      - ./shogun-nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
      - ./shogun-nginx/ssl/private/localhost.crt:/etc/nginx/ssl/private/localhost.crt
      - ./shogun-nginx/ssl/private/localhost.key:/etc/nginx/ssl/private/localhost.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - shogun-keycloak
      - shogun-boot
  shogun-boot:
    build:
      context: ../shogun/shogun-boot/
    ports:
      - "8080:8080"
      - "4711:4711"
      - "9010:9010"
    depends_on:
      - shogun-postgis
      - shogun-redis
      - shogun-keycloak
    volumes:
      - ../shogun/:/shogun/
      - ~/.m2:/root/.m2
      - ./shogun-boot/application.yml:/config/application.yml
      - ./shogun-boot/keystore/cacerts:/usr/lib/jvm/java-17-openjdk-amd64/lib/security/cacerts
    environment:
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_DISABLE_TRUST_MANAGER: ${KEYCLOAK_DISABLE_TRUST_MANAGER}
    volumes:
      - ../shogun/:/shogun/
      - ~/.m2:/root/.m2
      - ./shogun-boot/application.yml:/config/application.yml
      - ./shogun-boot/keystore/cacerts:/etc/pki/ca-trust/extracted/java/cacerts
    depends_on:
      - shogun-postgis
      - shogun-redis
      - shogun-keycloak
