version: '2'
services:
  shogun-boot:
    build:
      context: ../shogun/shogun-boot/
    ports:
      - "8080:8080"
      - "4711:4711"
      - "9010:9010"
    depends_on:
      - shogun-postgis
      - shogun-redis
      - shogun-keycloak
    volumes:
      - ../shogun/shogun-boot/:/shogun-boot/
      - ~/.m2:/root/.m2
