server:
  port: 8080
  servlet:
    context-path: /shogun-boot
    session:
      timeout: 86400
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    banner-mode: off
  jpa:
    # Show SQL statements
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: none
    properties:
      javax:
        persistence:
          sharedCache:
            # Only entities with @Cacheable annotation will use L2 cache
            mode: ENABLE_SELECTIVE
      org:
        hibernate:
          # See https://docs.jboss.org/envers/docs/#configuration
          envers:
            default_schema: shogun_rev
            audit_table_prefix: _rev
            global_with_modified_flag: true
      hibernate:
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: ehcache.xml
        format_sql: true
        # Generate statistics to check if L2/query cache is actually being used
        generate_statistics: true
        cache:
          # Enable L2 cache
          use_second_level_cache: true
          # Enable query cache
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        integration:
          envers:
            # Set this to false to disable auditing entity changes
            enabled: true
  messages:
    basename: org/springframework/security/messages, de/terrestris/shogun/lib/messages
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    defaultSchema: shogun
    schemas: shogun, public
  datasource:
    platform: postgres
    url: jdbc:postgresql://shogun-postgis:5432/shogun?currentSchema=shogun
    username: shogun
    password: shogun
  session:
    store-type: redis
  redis:
    host: shogun-redis
    port: 6379
    password: pass
  mail:
    host: mail.terrestris.de
    port: 587
    protocol: smtp
    username: noreply
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/auth
  realm: SpringBootKeycloak
  resource: shogun-app
  public-client: true
  ssl-required: external
  principal-attribute: preferred_username
  enable-basic-auth: true

keycloakauth:
  username: admin
  password: shogun
  master-realm: master
  admin-client: admin-cli

controller:
  applications:
    enabled: true
  auth:
    enabled: true
  cache:
    enabled: true
  files:
    enabled: true
  groups:
    enabled: true
  imagefiles:
    enabled: true
  info:
    enabled: true
  layers:
    enabled: true
  users:
    enabled: true

upload:
  file:
    supportedContentTypes:
      - application/json
      - application/pdf
      - application/xml
      - application/zip
      - text/comma-separated-values
      - text/plain
      - text/xml
  image:
    thumbnailSize: 100
    supportedContentTypes:
      - image/bmp
      - image/gif
      - image/jpeg
      - image/png
      - image/svg+xml
      - image/tiff
  basePath: /data
  maxSize: 500M

support:
  email: noreply@terrestris.de

management:
  endpoints:
    web:
      exposure:
        include: "*"
